#!/usr/bin/env python3

import argparse
import os

def read_config_file(config):
    parameters = []
    if not config:
        return parameters
    if not os.path.exists(config):
        return parameters
    with open(config, "r") as configfile:
        for line in configfile:
            line = line.strip()
            if line.startswith("#") or not line:
                continue
            parameters.append(line)
    return parameters

def run_command(command, parameters, prefix=[]):
    command_line = prefix + [command] + parameters
    os.execv(command_line[0], command_line)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("command", help="Path to executable")
    parser.add_argument(
        "config",
        help="Path to configuration file"
    )
    parser.add_argument(
        "--prefix",
        help="Path to configuration file containing the prefix"
    )
    args = parser.parse_args()
    prefix = read_config_file(args.prefix)
    parameters = read_config_file(args.config)
    run_command(args.command, parameters, prefix)